
import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import {
    Map, Building2, ChevronRight, CheckCircle2, BookOpen, Target, Lightbulb, Trophy,
    Code, Send, Loader2, Sparkles, Clock, Shield, Award, Plus, Trash2, Eye, X,
    ToggleLeft, ToggleRight, Users, XCircle, ChevronDown, ChevronUp, Search, BarChart2,
    MessageSquare, Brain, FileText
} from 'lucide-react';
import { InterviewChat } from './InterviewChat';
import { ReportView } from './ReportView';

const API = import.meta.env.VITE_API_URL || 'http://localhost:3000';

// ══════════════════════════════════════
//  COMPANY ROADMAP (Student)
// ══════════════════════════════════════
export function CompanyRoadmap({ user }) {
    const [companyName, setCompanyName] = useState('');
    const [roadmap, setRoadmap] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [questionBank, setQuestionBank] = useState(null);
    const [selectedYears, setSelectedYears] = useState(new Set([new Date().getFullYear()]));
    const [customYear, setCustomYear] = useState('');
    const [qbLoading, setQbLoading] = useState(false);
    const [expandedHints, setExpandedHints] = useState(new Set());
    const [previewMode, setPreviewMode] = useState(true);

    const toggleYear = (yr) => setSelectedYears(prev => {
        const n = new Set(prev);
        n.has(yr) ? n.delete(yr) : n.add(yr);
        return n;
    });

    const addCustomYear = () => {
        const yr = parseInt(customYear);
        if (yr >= 2000 && yr <= 2030) {
            setSelectedYears(prev => new Set([...prev, yr]));
            setCustomYear('');
        }
    };

    const fetchQuestionBank = async () => {
        const years = [...selectedYears].sort((a, b) => b - a);
        if (years.length === 0) return;
        setQbLoading(true);
        try {
            const { data } = await axios.get(`${API}/api/company/question-bank/${encodeURIComponent(companyName)}/${years[0]}`);
            setQuestionBank(data);
            setExpandedHints(new Set());
            setPreviewMode(true);
        } catch (e) { console.error(e); }
        finally { setQbLoading(false); }
    };

    const downloadPDF = () => {
        if (!questionBank?.rounds) return;
        const totalQ = questionBank.rounds.reduce((s, r) => s + (r.questions?.length || 0), 0);
        const html = `<html><head><title>${companyName} Question Bank ${[...selectedYears].join(', ')}</title>
        <style>body{font-family:'Segoe UI',sans-serif;padding:40px;color:#1e293b;max-width:900px;margin:0 auto}
        h1{font-size:28px;border-bottom:3px solid #3b82f6;padding-bottom:12px}
        h2{font-size:20px;color:#3b82f6;margin-top:32px;border-left:4px solid #3b82f6;padding-left:12px}
        .q{padding:14px 18px;margin:8px 0;border:1px solid #e2e8f0;border-radius:10px;border-left:4px solid #8b5cf6;page-break-inside:avoid}
        .tags{display:flex;gap:8px;margin-bottom:6px;flex-wrap:wrap}
        .tag{padding:2px 10px;border-radius:12px;font-size:11px;font-weight:700}
        .easy{background:#dcfce7;color:#16a34a}.medium{background:#fef3c7;color:#d97706}.hard{background:#fee2e2;color:#dc2626}
        .type{background:#e0e7ff;color:#4338ca}.topic{background:#f0f9ff;color:#0284c7}
        .hint{margin-top:8px;padding:8px 12px;background:#fffbeb;border:1px solid #fde68a;border-radius:8px;font-size:13px;color:#92400e}
        .stats{display:flex;gap:20px;margin:16px 0;font-size:14px;color:#64748b}
        @media print{body{padding:20px}.q{break-inside:avoid}}</style></head><body>
        <h1>📋 ${companyName} — Interview Question Bank</h1>
        <div class="stats"><span>📅 Year: ${[...selectedYears].join(', ')}</span><span>📝 Total: ${totalQ} Questions</span><span>🔄 ${questionBank.rounds.length} Rounds</span></div>
        ${questionBank.rounds.map(r => `<h2>${r.round_name} (${r.questions?.length || 0} Questions)</h2>
        ${(r.questions || []).map((q, i) => `<div class="q">
        <div class="tags"><span class="tag ${(q.difficulty || '').toLowerCase()}">${q.difficulty}</span><span class="tag type">${q.type}</span>${q.topic ? `<span class="tag topic">${q.topic}</span>` : ''}</div>
        <strong>Q${i + 1}.</strong> ${q.question}
        ${q.hint ? `<div class="hint">💡 Hint: ${q.hint}</div>` : ''}</div>`).join('')}`).join('')}
        <p style="margin-top:40px;text-align:center;color:#94a3b8;font-size:12px">Generated by MentorHub AI • ${new Date().toLocaleDateString()}</p></body></html>`;
        const w = window.open('', '_blank');
        w.document.write(html);
        w.document.close();
        setTimeout(() => w.print(), 500);
    };
    const popular = [
        { name: 'Google', color: '#4285F4', gradient: 'linear-gradient(135deg, #4285F4, #34A853)' },
        { name: 'Amazon', color: '#FF9900', gradient: 'linear-gradient(135deg, #FF9900, #FF6600)' },
        { name: 'Microsoft', color: '#00A4EF', gradient: 'linear-gradient(135deg, #00A4EF, #7FBA00)' },
        { name: 'Zoho', color: '#e42527', gradient: 'linear-gradient(135deg, #e42527, #ff6b6b)' },
        { name: 'TCS', color: '#0070C0', gradient: 'linear-gradient(135deg, #0070C0, #0090FF)' },
        { name: 'Infosys', color: '#007CC3', gradient: 'linear-gradient(135deg, #007CC3, #00B4D8)' },
        { name: 'Accenture', color: '#A100FF', gradient: 'linear-gradient(135deg, #A100FF, #7B2FBE)' },
        { name: 'Freshworks', color: '#F36F21', gradient: 'linear-gradient(135deg, #F36F21, #FF9A56)' },
        { name: 'Wipro', color: '#44184a', gradient: 'linear-gradient(135deg, #44184a, #6B3FA0)' },
        { name: 'HCL', color: '#0074BC', gradient: 'linear-gradient(135deg, #0074BC, #00A3E0)' },
        { name: 'CTS', color: '#0033A0', gradient: 'linear-gradient(135deg, #0033A0, #4169E1)' },
        { name: 'Capgemini', color: '#0070AD', gradient: 'linear-gradient(135deg, #0070AD, #12ABDB)' }
    ];

    const fetchRoadmap = async (name) => {
        if (!name.trim()) return;
        setLoading(true); setError(''); setCompanyName(name);
        try {
            const { data } = await axios.get(`${API}/api/company/roadmap/${encodeURIComponent(name)}`);
            setRoadmap(data);
        } catch (e) { setError(e.response?.data?.error || e.message); }
        finally { setLoading(false); }
    };

    if (!roadmap && !loading) {
        return (
            <div style={{ padding: '24px', maxWidth: '1100px', margin: '0 auto' }}>
                {/* Hero Section */}
                <div style={{
                    background: 'linear-gradient(135deg, rgba(59,130,246,0.12), rgba(139,92,246,0.08), rgba(236,72,153,0.06))',
                    border: '1px solid rgba(59,130,246,0.15)', borderRadius: '24px', padding: '48px 40px',
                    textAlign: 'center', marginBottom: '36px', position: 'relative', overflow: 'hidden'
                }}>
                    <div style={{ position: 'absolute', top: '-50%', right: '-20%', width: '400px', height: '400px', background: 'radial-gradient(circle, rgba(59,130,246,0.08) 0%, transparent 70%)', borderRadius: '50%' }} />
                    <div style={{ position: 'absolute', bottom: '-30%', left: '-10%', width: '300px', height: '300px', background: 'radial-gradient(circle, rgba(139,92,246,0.06) 0%, transparent 70%)', borderRadius: '50%' }} />
                    <div style={{ position: 'relative', zIndex: 1 }}>
                        <div style={{ width: '64px', height: '64px', background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)', borderRadius: '18px', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px', boxShadow: '0 8px 32px rgba(59,130,246,0.3)' }}>
                            <Map size={30} color="white" />
                        </div>
                        <h2 style={{ fontSize: '32px', fontWeight: 900, color: '#f1f5f9', marginBottom: '10px', letterSpacing: '-0.5px' }}>Company Preparation Roadmap</h2>
                        <p style={{ color: '#94a3b8', fontSize: '15px', maxWidth: '500px', margin: '0 auto 28px', lineHeight: '1.6' }}>
                            Enter any company name to get an AI-curated placement roadmap with hiring process, preparation strategy & interview tips
                        </p>
                        <div style={{ display: 'flex', gap: '10px', maxWidth: '520px', margin: '0 auto' }}>
                            <div style={{ flex: 1, position: 'relative' }}>
                                <Search size={18} style={{ position: 'absolute', left: '16px', top: '50%', transform: 'translateY(-50%)', color: '#64748b', pointerEvents: 'none' }} />
                                <input value={companyName} onChange={e => setCompanyName(e.target.value)}
                                    onKeyDown={e => e.key === 'Enter' && fetchRoadmap(companyName)}
                                    placeholder="Type any company (Flipkart, Paytm, Razorpay...)"
                                    style={{ width: '100%', padding: '16px 18px 16px 48px', borderRadius: '14px', border: '2px solid rgba(59,130,246,0.3)', background: '#0f172a', color: '#f1f5f9', fontSize: '15px', outline: 'none', boxSizing: 'border-box', transition: 'border-color 0.2s' }}
                                    onFocus={e => e.target.style.borderColor = '#3b82f6'}
                                    onBlur={e => e.target.style.borderColor = 'rgba(59,130,246,0.3)'} />
                            </div>
                            <button onClick={() => fetchRoadmap(companyName)} style={{
                                padding: '16px 32px', background: 'linear-gradient(135deg, #3b82f6, #2563eb)', color: 'white',
                                border: 'none', borderRadius: '14px', fontWeight: 700, cursor: 'pointer', fontSize: '15px',
                                display: 'flex', alignItems: 'center', gap: '8px', boxShadow: '0 4px 16px rgba(59,130,246,0.3)',
                                transition: 'transform 0.15s, box-shadow 0.15s', whiteSpace: 'nowrap'
                            }}
                                onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 6px 24px rgba(59,130,246,0.4)'; }}
                                onMouseLeave={e => { e.currentTarget.style.transform = 'none'; e.currentTarget.style.boxShadow = '0 4px 16px rgba(59,130,246,0.3)'; }}>
                                Generate <Sparkles size={16} />
                            </button>
                        </div>
                    </div>
                </div>

                {error && <div style={{ color: '#fca5a5', textAlign: 'center', marginBottom: '16px', fontSize: '13px', padding: '10px', background: 'rgba(239,68,68,0.08)', borderRadius: '10px', border: '1px solid rgba(239,68,68,0.2)' }}><XCircle size={14} style={{ verticalAlign: 'middle', marginRight: '6px' }} />{error}</div>}

                {/* Popular Companies Header */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
                    <div style={{ height: '1px', flex: 1, background: 'linear-gradient(90deg, transparent, #334155)' }} />
                    <span style={{ fontSize: '12px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '1.5px' }}>Popular Companies</span>
                    <div style={{ height: '1px', flex: 1, background: 'linear-gradient(90deg, #334155, transparent)' }} />
                </div>

                {/* Company Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: '14px' }}>
                    {popular.map(c => (
                        <button key={c.name} onClick={() => fetchRoadmap(c.name)}
                            style={{
                                padding: '22px 14px', background: '#1e293b', border: '1px solid #334155',
                                borderRadius: '16px', cursor: 'pointer', textAlign: 'center', transition: 'all 0.25s ease',
                                position: 'relative', overflow: 'hidden'
                            }}
                            onMouseEnter={e => {
                                e.currentTarget.style.borderColor = c.color;
                                e.currentTarget.style.transform = 'translateY(-4px)';
                                e.currentTarget.style.boxShadow = `0 8px 30px ${c.color}20`;
                                e.currentTarget.querySelector('.company-icon').style.transform = 'scale(1.15)';
                            }}
                            onMouseLeave={e => {
                                e.currentTarget.style.borderColor = '#334155';
                                e.currentTarget.style.transform = 'none';
                                e.currentTarget.style.boxShadow = 'none';
                                e.currentTarget.querySelector('.company-icon').style.transform = 'none';
                            }}>
                            <div className="company-icon" style={{
                                width: '44px', height: '44px', borderRadius: '12px', margin: '0 auto 12px',
                                background: c.gradient, display: 'flex', alignItems: 'center', justifyContent: 'center',
                                boxShadow: `0 4px 12px ${c.color}30`, transition: 'transform 0.25s'
                            }}>
                                <Building2 size={22} color="white" />
                            </div>
                            <div style={{ fontWeight: 700, fontSize: '14px', color: '#e2e8f0' }}>{c.name}</div>
                            <div style={{ fontSize: '10px', color: '#64748b', marginTop: '4px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>
                                <Sparkles size={10} /> AI Roadmap
                            </div>
                        </button>
                    ))}
                </div>

                {/* Footer hint */}
                <div style={{ textAlign: 'center', marginTop: '32px', color: '#475569', fontSize: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}>
                    <Lightbulb size={14} /> Tip: You can type any company name — even startups. Our AI will generate a custom roadmap!
                </div>
            </div>
        );
    }

    if (loading) return <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '400px', gap: '16px' }}><Loader2 size={44} color="#3b82f6" style={{ animation: 'spin 1s linear infinite' }} /><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style><p style={{ color: '#94a3b8', fontWeight: 700, fontSize: '16px' }}>AI is curating your {companyName} roadmap...</p><p style={{ color: '#64748b', fontSize: '13px' }}>This may take 10-15 seconds</p></div>;

    const SectionCard = ({ icon, title, color, badge, children }) => (
        <div style={{ background: 'linear-gradient(145deg, #1e293b, #0f172a)', border: '1px solid #334155', borderRadius: '20px', overflow: 'hidden', marginBottom: '20px', transition: 'border-color 0.3s' }}>
            <div style={{ padding: '20px 28px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid rgba(255,255,255,0.05)', background: `linear-gradient(90deg, ${color}08, transparent)` }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: `${color}15`, color, border: `1px solid ${color}30` }}>{icon}</div>
                    <span style={{ fontWeight: 800, fontSize: '19px', color: '#f1f5f9', letterSpacing: '-0.3px', fontFamily: "'Inter', 'Segoe UI', sans-serif" }}>{title}</span>
                </div>
                {badge && <span style={{ fontSize: '11px', fontWeight: 700, padding: '5px 14px', borderRadius: '20px', background: `${color}15`, color, border: `1px solid ${color}30`, textTransform: 'uppercase', letterSpacing: '0.5px' }}>{badge}</span>}
            </div>
            <div style={{ padding: '22px 28px' }}>{children}</div>
        </div>
    );

    const hiringSteps = roadmap?.hiring_process || [];
    const tips = roadmap?.interview_tips || [];
    const metrics = roadmap?.success_metrics || [];
    const strategy = roadmap?.preparation_strategy || [];
    const topics = roadmap?.important_topics || [];
    const questions = roadmap?.previous_year_questions || [];

    const phaseColors = ['#3B82F6', '#8B5CF6', '#EC4899', '#F59E0B', '#10B981', '#06B6D4', '#EF4444', '#84CC16', '#F97316', '#6366F1', '#14B8A6', '#E879F9'];

    return (
        <div style={{ padding: '28px', maxWidth: '1280px', margin: '0 auto' }}>
            {/* Back Button */}
            <button onClick={() => { setRoadmap(null); setCompanyName(''); }} style={{ display: 'flex', alignItems: 'center', gap: '8px', background: '#1e293b', border: '1px solid #334155', borderRadius: '12px', padding: '10px 20px', color: '#94a3b8', cursor: 'pointer', fontWeight: 700, fontSize: '14px', marginBottom: '24px', transition: 'all 0.2s' }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = '#3b82f6'; e.currentTarget.style.color = '#f1f5f9'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = '#334155'; e.currentTarget.style.color = '#94a3b8'; }}
            >← Back to Companies</button>

            {/* Hero Header */}
            <div style={{ background: 'linear-gradient(135deg, rgba(59,130,246,0.12), rgba(139,92,246,0.08), rgba(16,185,129,0.05))', border: '1px solid rgba(59,130,246,0.2)', borderRadius: '24px', padding: '36px 40px', display: 'flex', gap: '24px', alignItems: 'center', marginBottom: '32px', position: 'relative', overflow: 'hidden' }}>
                <div style={{ position: 'absolute', top: '-50%', right: '-10%', width: '300px', height: '300px', background: 'radial-gradient(circle, rgba(139,92,246,0.06) 0%, transparent 70%)', borderRadius: '50%' }} />
                <div style={{ width: '64px', height: '64px', background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)', borderRadius: '18px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, boxShadow: '0 8px 24px rgba(59,130,246,0.3)' }}><Building2 size={30} color="white" /></div>
                <div style={{ position: 'relative', zIndex: 1 }}>
                    <h1 style={{ margin: 0, fontSize: '30px', fontWeight: 900, color: '#f1f5f9', letterSpacing: '-0.5px' }}>{companyName} Placement Roadmap</h1>
                    <p style={{ margin: '8px 0 0', color: '#94a3b8', fontSize: '15px', lineHeight: '1.7', maxWidth: '700px' }}>{roadmap?.company_overview || ''}</p>
                </div>
            </div>

            {/* ===== SECTION 1: Hiring Process (Full Width) ===== */}
            <SectionCard icon={<Target size={18} />} title="Hiring Process" color="#3B82F6" badge={`${hiringSteps.length} Rounds`}>
                <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0', overflowX: 'auto', paddingBottom: '8px' }}>
                    {hiringSteps.map((step, i) => (
                        <div key={i} style={{ display: 'flex', alignItems: 'center', flexShrink: 0 }}>
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px', minWidth: '140px', textAlign: 'center' }}>
                                <div style={{ width: '44px', height: '44px', borderRadius: '50%', background: `${phaseColors[i % phaseColors.length]}18`, border: `2px solid ${phaseColors[i % phaseColors.length]}50`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '16px', fontWeight: 900, color: phaseColors[i % phaseColors.length] }}>
                                    {i + 1}
                                </div>
                                <span style={{ fontSize: '14px', color: '#e2e8f0', fontWeight: 600, lineHeight: '1.5', maxWidth: '130px' }}>{step}</span>
                            </div>
                            {i < hiringSteps.length - 1 && (
                                <div style={{ width: '40px', height: '2px', background: 'linear-gradient(90deg, #334155, #475569, #334155)', flexShrink: 0, marginTop: '-20px' }} />
                            )}
                        </div>
                    ))}
                </div>
            </SectionCard>

            {/* ===== ROW 2: Tips + Success Metrics ===== */}
            <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: '20px' }}>
                <SectionCard icon={<Lightbulb size={18} />} title="Interview Tips" color="#F59E0B" badge={`${tips.length} Tips`}>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                        {tips.map((tip, i) => (
                            <div key={i} style={{ display: 'flex', gap: '12px', padding: '14px 16px', background: '#0f172a', borderRadius: '14px', border: '1px solid #1e293b', transition: 'border-color 0.2s' }}>
                                <div style={{ width: '28px', height: '28px', borderRadius: '8px', background: '#F59E0B15', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, border: '1px solid #F59E0B30' }}>
                                    <CheckCircle2 size={14} color="#F59E0B" />
                                </div>
                                <span style={{ fontSize: '15px', color: '#cbd5e1', lineHeight: '1.7', fontWeight: 500 }}>{tip}</span>
                            </div>
                        ))}
                    </div>
                </SectionCard>

                <SectionCard icon={<Award size={18} />} title="Success Metrics" color="#8B5CF6" badge="What Recruiters Want">
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                        {metrics.map((m, i) => (
                            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 16px', background: '#0f172a', borderRadius: '12px', border: '1px solid #1e293b' }}>
                                <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: phaseColors[i % phaseColors.length], boxShadow: `0 0 8px ${phaseColors[i % phaseColors.length]}60`, flexShrink: 0 }} />
                                <span style={{ fontSize: '15px', color: '#cbd5e1', fontWeight: 500, lineHeight: '1.6' }}>{m}</span>
                            </div>
                        ))}
                    </div>
                </SectionCard>
            </div>

            {/* ===== SECTION 3: Preparation Strategy (Full Width) ===== */}
            <SectionCard icon={<Map size={18} />} title="Preparation Strategy" color="#10B981" badge={`${strategy.length}-Week Plan`}>
                <div style={{ position: 'relative', paddingLeft: '32px' }}>
                    <div style={{ position: 'absolute', left: '11px', top: '12px', bottom: '12px', width: '3px', background: 'linear-gradient(180deg, #3b82f6, #8b5cf6, #ec4899, #10b981, transparent)', borderRadius: '2px' }} />
                    {strategy.map((p, i) => (
                        <div key={i} style={{ position: 'relative', marginBottom: '20px' }}>
                            <div style={{ position: 'absolute', left: '-32px', top: '18px', width: '14px', height: '14px', borderRadius: '50%', background: '#020617', border: `3px solid ${phaseColors[i % phaseColors.length]}`, zIndex: 1, boxShadow: `0 0 10px ${phaseColors[i % phaseColors.length]}40` }} />
                            <div style={{ background: '#020617', border: '1px solid #1e293b', borderLeft: `4px solid ${phaseColors[i % phaseColors.length]}`, borderRadius: '14px', padding: '18px 22px', transition: 'border-color 0.2s' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                                    <span style={{ fontSize: '11px', fontWeight: 800, color: phaseColors[i % phaseColors.length], textTransform: 'uppercase', letterSpacing: '0.8px', padding: '3px 10px', background: `${phaseColors[i % phaseColors.length]}12`, borderRadius: '6px' }}>{p.phase}</span>
                                </div>
                                <h4 style={{ margin: '0 0 10px', fontSize: '18px', fontWeight: 800, color: '#f1f5f9', letterSpacing: '-0.2px' }}>{p.topic}</h4>
                                <p style={{ margin: '0 0 12px', color: '#94a3b8', fontSize: '15px', lineHeight: '1.7' }}>{p.goal}</p>
                                <div style={{ display: 'flex', alignItems: 'flex-start', gap: '6px', padding: '10px 14px', background: '#0f172a60', borderRadius: '10px', border: '1px solid #1e293b' }}>
                                    <BookOpen size={14} color="#3b82f6" style={{ marginTop: '2px', flexShrink: 0 }} />
                                    <span style={{ fontSize: '14px', color: '#60a5fa', lineHeight: '1.6' }}>{p.resources}</span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </SectionCard>

            {/* ===== Must-Know Topics (Full Width, 2-col internal grid) ===== */}
            <SectionCard icon={<Code size={20} />} title="Must-Know Topics" color="#22C55E" badge={`${topics.length} Categories`}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px 32px' }}>
                    {topics.map((item, i) => (
                        <div key={i}>
                            <div style={{ fontSize: '13px', fontWeight: 800, color: phaseColors[i % phaseColors.length], textTransform: 'uppercase', marginBottom: '10px', letterSpacing: '0.8px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                                <div style={{ width: '4px', height: '18px', borderRadius: '2px', background: phaseColors[i % phaseColors.length] }} />
                                {item.subject}
                            </div>
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '7px' }}>
                                {(item.topics || []).map((t, j) => (
                                    <span key={j} style={{ padding: '6px 14px', background: '#020617', borderRadius: '10px', fontSize: '13px', color: '#e2e8f0', border: '1px solid #1e293b', fontWeight: 500, transition: 'all 0.2s', cursor: 'default' }}
                                        onMouseEnter={e => { e.currentTarget.style.borderColor = phaseColors[i % phaseColors.length]; e.currentTarget.style.background = `${phaseColors[i % phaseColors.length]}08`; }}
                                        onMouseLeave={e => { e.currentTarget.style.borderColor = '#1e293b'; e.currentTarget.style.background = '#020617'; }}
                                    >{t}</span>
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </SectionCard>

            {/* ===== QUESTION BANK — Full Width, Multi-Year, Preview + PDF ===== */}
            <SectionCard icon={<FileText size={20} />} title="Previous Year Question Bank" color="#EC4899" badge="50+ Per Year">
                {/* Year Selection Bar */}
                <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '12px', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '14px', fontWeight: 700, color: '#e2e8f0' }}>Select Year(s):</span>
                    {[2026, 2025, 2024, 2023, 2022, 2021, 2020, 2019].map(yr => (
                        <button key={yr} onClick={() => toggleYear(yr)} style={{
                            padding: '8px 18px', borderRadius: '10px', fontSize: '14px', fontWeight: 700, cursor: 'pointer', transition: 'all 0.2s',
                            border: selectedYears.has(yr) ? '2px solid #EC4899' : '1px solid #334155',
                            background: selectedYears.has(yr) ? '#EC489918' : '#020617',
                            color: selectedYears.has(yr) ? '#EC4899' : '#94a3b8'
                        }}>{yr}</button>
                    ))}
                    <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
                        <input value={customYear} onChange={e => setCustomYear(e.target.value)} placeholder="Other year" onKeyDown={e => e.key === 'Enter' && addCustomYear()}
                            style={{ width: '90px', padding: '8px 12px', borderRadius: '10px', border: '1px solid #334155', background: '#020617', color: '#f1f5f9', fontSize: '13px', outline: 'none' }} />
                        <button onClick={addCustomYear} style={{ padding: '8px 12px', borderRadius: '10px', border: '1px solid #334155', background: '#1e293b', color: '#94a3b8', fontSize: '13px', cursor: 'pointer', fontWeight: 700 }}>+</button>
                    </div>
                </div>
                <div style={{ display: 'flex', gap: '10px', alignItems: 'center', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '13px', color: '#64748b' }}>{selectedYears.size} year(s) selected</span>
                    <button onClick={fetchQuestionBank} disabled={qbLoading || selectedYears.size === 0} style={{
                        padding: '10px 28px', borderRadius: '12px', border: 'none', fontWeight: 800, fontSize: '14px', cursor: qbLoading ? 'not-allowed' : 'pointer',
                        background: qbLoading ? '#475569' : 'linear-gradient(135deg, #EC4899, #DB2777)', color: 'white',
                        display: 'flex', alignItems: 'center', gap: '8px', boxShadow: '0 4px 16px rgba(236,72,153,0.3)', marginLeft: 'auto'
                    }}>
                        {qbLoading ? <><Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> Generating 50+ Questions...</> : <><Sparkles size={16} /> Generate Question Bank</>}
                    </button>
                </div>

                {/* Loading */}
                {qbLoading && (
                    <div style={{ textAlign: 'center', padding: '50px 20px', color: '#94a3b8' }}>
                        <Loader2 size={36} color="#EC4899" style={{ animation: 'spin 1s linear infinite', marginBottom: '12px' }} />
                        <p style={{ fontWeight: 700, fontSize: '16px' }}>AI is generating {companyName}'s question bank...</p>
                        <p style={{ fontSize: '14px', color: '#64748b' }}>Generating 50+ questions across all rounds • This may take 15-20 seconds</p>
                    </div>
                )}

                {/* Empty State */}
                {!qbLoading && !questionBank && (
                    <div style={{ textAlign: 'center', padding: '50px 20px', background: '#020617', borderRadius: '16px', border: '1px dashed #334155', marginTop: '16px' }}>
                        <FileText size={42} color="#475569" style={{ marginBottom: '14px' }} />
                        <p style={{ color: '#e2e8f0', fontSize: '16px', fontWeight: 700, marginBottom: '6px' }}>No questions generated yet</p>
                        <p style={{ color: '#64748b', fontSize: '14px' }}>Select year(s) above and click "Generate Question Bank" to get {companyName}'s full interview question bank</p>
                    </div>
                )}

                {/* Results */}
                {!qbLoading && questionBank && questionBank.rounds && (() => {
                    const totalQ = questionBank.rounds.reduce((s, r) => s + (r.questions?.length || 0), 0);
                    return (
                        <div style={{ marginTop: '16px' }}>
                            {/* Stats + Actions Bar */}
                            <div style={{ display: 'flex', gap: '12px', marginBottom: '20px', flexWrap: 'wrap', alignItems: 'center' }}>
                                <span style={{ padding: '6px 16px', borderRadius: '20px', background: '#EC489915', color: '#EC4899', fontSize: '13px', fontWeight: 700, border: '1px solid #EC489930' }}>
                                    📝 {totalQ} Questions
                                </span>
                                <span style={{ padding: '6px 16px', borderRadius: '20px', background: '#3B82F615', color: '#3B82F6', fontSize: '13px', fontWeight: 700, border: '1px solid #3B82F630' }}>
                                    🔄 {questionBank.rounds.length} Rounds
                                </span>
                                <span style={{ padding: '6px 16px', borderRadius: '20px', background: '#10B98115', color: '#10B981', fontSize: '13px', fontWeight: 700, border: '1px solid #10B98130' }}>
                                    📅 {[...selectedYears].sort((a, b) => b - a).join(', ')}
                                </span>
                                <div style={{ marginLeft: 'auto', display: 'flex', gap: '10px' }}>
                                    <button onClick={() => setPreviewMode(!previewMode)} style={{
                                        padding: '8px 18px', borderRadius: '10px', border: '1px solid #334155', background: '#1e293b',
                                        color: '#e2e8f0', fontSize: '13px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px'
                                    }}><Eye size={14} /> {previewMode ? 'Show All' : 'Preview Mode'}</button>
                                    <button onClick={downloadPDF} style={{
                                        padding: '8px 20px', borderRadius: '10px', border: 'none',
                                        background: 'linear-gradient(135deg, #3B82F6, #2563EB)', color: 'white',
                                        fontSize: '13px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px',
                                        boxShadow: '0 4px 12px rgba(59,130,246,0.3)'
                                    }}><FileText size={14} /> Download as PDF</button>
                                </div>
                            </div>

                            {/* Questions by Round */}
                            {questionBank.rounds.map((round, ri) => {
                                const visibleQ = previewMode ? (round.questions || []).slice(0, 3) : (round.questions || []);
                                const hiddenCount = (round.questions?.length || 0) - visibleQ.length;
                                return (
                                    <div key={ri} style={{ marginBottom: '24px' }}>
                                        <div style={{ fontSize: '15px', fontWeight: 800, color: phaseColors[ri % phaseColors.length], textTransform: 'uppercase', marginBottom: '12px', letterSpacing: '0.5px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                                            <div style={{ width: '5px', height: '20px', borderRadius: '2px', background: phaseColors[ri % phaseColors.length] }} />
                                            {round.round_name}
                                            <span style={{ fontSize: '12px', fontWeight: 600, color: '#64748b', background: '#1e293b', padding: '3px 10px', borderRadius: '8px', textTransform: 'lowercase' }}>{round.questions?.length || 0} questions</span>
                                        </div>
                                        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                                            {visibleQ.map((q, qi) => {
                                                const globalIdx = `${ri}-${qi}`;
                                                const diffColor = q.difficulty === 'Hard' ? '#EF4444' : q.difficulty === 'Medium' ? '#F59E0B' : '#22C55E';
                                                return (
                                                    <div key={qi} style={{ padding: '16px 20px', background: '#020617', borderRadius: '14px', border: '1px solid #1e293b', borderLeft: `4px solid ${phaseColors[ri % phaseColors.length]}` }}>
                                                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px', gap: '8px', flexWrap: 'wrap' }}>
                                                            <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                                                                <span style={{ fontSize: '11px', padding: '4px 12px', background: `${diffColor}15`, color: diffColor, borderRadius: '8px', fontWeight: 700 }}>{q.difficulty}</span>
                                                                <span style={{ fontSize: '11px', padding: '4px 12px', background: '#1e293b', color: '#94a3b8', borderRadius: '8px', fontWeight: 700, textTransform: 'uppercase' }}>{q.type}</span>
                                                                {q.topic && <span style={{ fontSize: '11px', padding: '4px 12px', background: '#3B82F610', color: '#60a5fa', borderRadius: '8px', fontWeight: 600 }}>{q.topic}</span>}
                                                            </div>
                                                            {q.hint && <button onClick={() => setExpandedHints(prev => {
                                                                const n = new Set(prev); n.has(globalIdx) ? n.delete(globalIdx) : n.add(globalIdx); return n;
                                                            })} style={{ background: 'none', border: 'none', color: '#F59E0B', fontSize: '12px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                                <Lightbulb size={13} /> {expandedHints.has(globalIdx) ? 'Hide Hint' : 'Show Hint'}
                                                            </button>}
                                                        </div>
                                                        <p style={{ margin: 0, fontSize: '15px', color: '#e2e8f0', lineHeight: '1.7', fontWeight: 500 }}>{q.question}</p>
                                                        {expandedHints.has(globalIdx) && q.hint && (
                                                            <div style={{ marginTop: '10px', padding: '10px 16px', background: '#F59E0B08', borderRadius: '10px', border: '1px solid #F59E0B20', fontSize: '14px', color: '#fbbf24', display: 'flex', gap: '8px', alignItems: 'flex-start' }}>
                                                                <Lightbulb size={15} style={{ marginTop: '2px', flexShrink: 0 }} />
                                                                <span>{q.hint}</span>
                                                            </div>
                                                        )}
                                                    </div>
                                                );
                                            })}
                                            {previewMode && hiddenCount > 0 && (
                                                <div style={{ textAlign: 'center', padding: '12px', background: '#0f172a', borderRadius: '12px', border: '1px dashed #334155' }}>
                                                    <span style={{ color: '#64748b', fontSize: '14px', fontWeight: 600 }}>+ {hiddenCount} more questions </span>
                                                    <button onClick={() => setPreviewMode(false)} style={{ background: 'none', border: 'none', color: '#EC4899', fontWeight: 700, fontSize: '14px', cursor: 'pointer', textDecoration: 'underline' }}>Show All</button>
                                                    <span style={{ color: '#64748b', fontSize: '13px' }}> or </span>
                                                    <button onClick={downloadPDF} style={{ background: 'none', border: 'none', color: '#3B82F6', fontWeight: 700, fontSize: '14px', cursor: 'pointer', textDecoration: 'underline' }}>Download PDF</button>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    );
                })()}
            </SectionCard>
        </div>
    );
}

// ══════════════════════════════════════
//  COMPANY PREP - Student Interview
// ══════════════════════════════════════
export function CompanyPrep({ user }) {
    const [tests, setTests] = useState([]);
    const [attempt, setAttempt] = useState(null);
    const [history, setHistory] = useState([]);
    const [loading, setLoading] = useState(true);
    const [viewReport, setViewReport] = useState(null);

    useEffect(() => {
        Promise.all([
            axios.get(`${API}/api/company/interviews`),
            (user?.id || user?.userId) ? axios.get(`${API}/api/company/interviews/student/${user?.id || user?.userId}/history`) : Promise.resolve({ data: [] })
        ]).then(([t, h]) => { setTests(t.data); setHistory(h.data); }).finally(() => setLoading(false));
    }, []);

    const startTest = async (testId) => {
        try {
            const parsedId = user?.id || user?.userId;
            const { data } = await axios.post(`${API}/api/company/interviews/${testId}/start`, { studentId: parsedId, studentName: user?.name || 'Student' });
            setAttempt({
                id: data.attemptId,
                companyName: data.companyName,
                messages: [{ role: 'assistant', content: data.initialMessage }],
                interview_progress: data.interview_progress || 0
            });
        } catch (e) { alert('Failed to start: ' + (e.response?.data?.error || e.message)); }
    };

    const deleteAttempt = async (id) => {
        if (!confirm('Permanently delete this interview attempt?')) return;
        try {
            await axios.delete(`${API}/api/company/interviews/attempt/${id}`);
            setHistory(prev => prev.filter(h => h.id !== id));
        } catch (e) {
            alert('Failed to delete attempt');
        }
    };

    if (attempt) return <InterviewChat attempt={attempt} onClose={(evalData) => { setAttempt(null); if (evalData) setViewReport(evalData); }} />;

    if (viewReport) return <ReportView report={viewReport} onClose={() => { setViewReport(null); setLoading(true); axios.get(`${API}/api/company/interviews/student/${user?.id || user?.userId}/history`).then(r => setHistory(r.data)).finally(() => setLoading(false)); }} />;

    if (loading) return <div style={{ display: 'flex', justifyContent: 'center', padding: '80px' }}><Loader2 size={36} color="#3b82f6" style={{ animation: 'spin 1s linear infinite' }} /><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style></div>;

    return (
        <div style={{ padding: '24px', maxWidth: '1200px', margin: '0 auto' }}>
            <h2 style={{ fontSize: '22px', fontWeight: 800, color: '#f1f5f9', marginBottom: '6px' }}>Company Interview Prep</h2>
            <p style={{ color: '#94a3b8', fontSize: '13px', marginBottom: '24px' }}>Practice with AI-powered mock interviews tailored to specific companies</p>
            {tests.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '60px', background: '#1e293b', borderRadius: '16px', border: '1px dashed #475569' }}>
                    <Building2 size={48} color="#475569" style={{ marginBottom: '12px' }} />
                    <p style={{ color: '#94a3b8' }}>No company tests available yet. Ask your admin to create one.</p>
                </div>
            ) : (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '16px', marginBottom: '32px' }}>
                    {tests.map(t => {
                        const attemptsMade = history.filter(h => h.test_id === t.id).length;
                        const canAttempt = t.max_attempts === 0 || attemptsMade < t.max_attempts;

                        return (
                            <div key={t.id} style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '14px', padding: '20px', display: 'flex', flexDirection: 'column' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '14px' }}>
                                    <div style={{ width: '40px', height: '40px', background: '#3b82f620', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Building2 size={20} color="#3b82f6" /></div>
                                    <span style={{ padding: '3px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: 700, background: t.difficulty === 'hard' ? '#ef444420' : t.difficulty === 'medium' ? '#f59e0b20' : '#22c55e20', color: t.difficulty === 'hard' ? '#f87171' : t.difficulty === 'medium' ? '#fbbf24' : '#4ade80' }}>{t.difficulty}</span>
                                </div>
                                <h3 style={{ margin: '0 0 4px', fontSize: '16px', fontWeight: 800, color: '#f1f5f9' }}>{t.title}</h3>
                                <span style={{ fontSize: '10px', color: '#3b82f6', fontWeight: 700, textTransform: 'uppercase', marginBottom: '8px' }}>{t.company_name}</span>
                                <p style={{ color: '#94a3b8', fontSize: '12px', lineHeight: '1.5', flex: 1, marginBottom: '14px' }}>{t.description}</p>
                                <div style={{ display: 'flex', gap: '12px', marginBottom: '14px', fontSize: '11px', color: '#64748b', flexWrap: 'wrap' }}>
                                    <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Clock size={12} /> {t.duration_minutes}m</span>
                                    <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Shield size={12} /> AI Evaluated</span>
                                    <span style={{ display: 'flex', alignItems: 'center', gap: '4px', color: canAttempt ? '#64748b' : '#ef4444' }}>
                                        <Users size={12} /> Attempts: {t.max_attempts > 0 ? `${attemptsMade}/${t.max_attempts}` : 'Unlimited'}
                                    </span>
                                </div>
                                {canAttempt ? (
                                    <button onClick={() => startTest(t.id)} style={{ width: '100%', padding: '11px', background: 'linear-gradient(135deg, #3b82f6, #2563eb)', color: 'white', border: 'none', borderRadius: '10px', fontWeight: 700, fontSize: '14px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}>Start Interview <ChevronRight size={16} /></button>
                                ) : (
                                    <button disabled style={{ width: '100%', padding: '11px', background: '#334155', color: '#94a3b8', border: '1px solid #475569', borderRadius: '10px', fontWeight: 700, fontSize: '14px', cursor: 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}>Limit Reached</button>
                                )}
                            </div>
                        );
                    })}
                </div>
            )}
            {history.length > 0 && (
                <div>
                    <h3 style={{ fontSize: '16px', fontWeight: 700, color: '#e2e8f0', marginBottom: '12px' }}>Past Attempts</h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                        {history.map(h => (
                            <div key={h.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 18px', background: '#1e293b', border: '1px solid #334155', borderRadius: '10px' }}>
                                <div><span style={{ fontWeight: 700, color: '#f1f5f9', fontSize: '14px' }}>{h.title}</span><span style={{ fontSize: '11px', color: '#3b82f6', fontWeight: 600, marginLeft: '8px' }}>{h.company_name}</span></div>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                                    <span style={{ padding: '3px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: 700, background: h.status === 'completed' ? '#22c55e20' : '#f59e0b20', color: h.status === 'completed' ? '#4ade80' : '#fbbf24' }}>{h.status}</span>
                                    {h.status === 'completed' ? (
                                        <span style={{ fontWeight: 800, color: '#f1f5f9', fontSize: '13px' }}>{Math.round(h.overall_score || 0)}%</span>
                                    ) : (
                                        <span style={{ fontWeight: 700, color: '#3b82f6', fontSize: '12px' }}>{h.interview_progress || 0}% Done</span>
                                    )}
                                    {h.evaluation_report && <button onClick={() => setViewReport(h.evaluation_report)} style={{ padding: '6px 12px', background: '#3b82f620', border: '1px solid #3b82f640', borderRadius: '8px', color: '#60a5fa', fontSize: '12px', fontWeight: 600, cursor: 'pointer' }}>View Report</button>}
                                    <button onClick={() => deleteAttempt(h.id)} style={{ padding: '6px', background: 'transparent', border: 'none', color: '#f87171', cursor: 'pointer', opacity: 0.6 }} title="Delete Attempt"><Trash2 size={16} /></button>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
}

// New standalone InterviewChat and ReportView components are imported above.

// ══════════════════════════════════════
//  COMPANY TEST MANAGER (Admin)
// ══════════════════════════════════════
export function CompanyTestManager() {
    const [tests, setTests] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showCreate, setShowCreate] = useState(false);
    const [creating, setCreating] = useState(false);
    const [error, setError] = useState('');
    const [viewAttempts, setViewAttempts] = useState(null);
    const [attempts, setAttempts] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');
    const [form, setForm] = useState({ company_name: '', title: '', description: '', duration_minutes: 60, difficulty: 'medium', skills_covered: [], max_attempts: 0 });
    const [editingLimit, setEditingLimit] = useState(null);
    const [limitValue, setLimitValue] = useState(0);
    const [assignModal, setAssignModal] = useState(null);
    const [allStudents, setAllStudents] = useState([]);
    const [selectedStudents, setSelectedStudents] = useState([]);
    const [studentSearch, setStudentSearch] = useState('');

    const load = () => { setLoading(true); axios.get(`${API}/api/company/interviews/all`).then(r => setTests(r.data)).catch(e => setError(e.message)).finally(() => setLoading(false)); };
    useEffect(load, []);

    const create = async () => {
        if (!form.company_name.trim() || !form.title.trim()) return setError('Company name and title required');
        setCreating(true); setError('');
        try { await axios.post(`${API}/api/company/interviews/create`, form); setShowCreate(false); setForm({ company_name: '', title: '', description: '', duration_minutes: 60, difficulty: 'medium', skills_covered: [], max_attempts: 0 }); load(); }
        catch (e) { setError(e.response?.data?.error || e.message); }
        finally { setCreating(false); }
    };

    const toggle = async (id) => { try { await axios.put(`${API}/api/company/interviews/${id}/toggle`); load(); } catch (e) { setError(e.message); } };
    const del = async (id) => { if (!confirm('Delete this test and all attempts?')) return; try { await axios.delete(`${API}/api/company/interviews/${id}`); load(); } catch (e) { setError(e.message); } };
    const loadAttempts = async (id) => {
        if (viewAttempts === id) { setViewAttempts(null); return; }
        try { const { data } = await axios.get(`${API}/api/company/interviews/${id}/attempts`); setAttempts(data); setViewAttempts(id); }
        catch (e) { setAttempts([]); setViewAttempts(id); }
    };

    const saveLimit = async (id) => {
        try { await axios.put(`${API}/api/company/interviews/${id}/update-limits`, { max_attempts: parseInt(limitValue) || 0 }); setEditingLimit(null); load(); }
        catch (e) { setError(e.message); }
    };

    const openAssignModal = async (testId) => {
        try {
            const { data } = await axios.get(`${API}/api/company/students`);
            setAllStudents(data);
            const test = tests.find(t => t.id === testId);
            const assigned = test?.assigned_students || [];
            setSelectedStudents(Array.isArray(assigned) ? assigned.map(id => parseInt(id)) : []);
            setAssignModal(testId);
            setStudentSearch('');
        } catch (e) { setError(e.message); }
    };

    const saveAssignment = async () => {
        try { await axios.put(`${API}/api/company/interviews/${assignModal}/assign`, { student_ids: selectedStudents }); setAssignModal(null); load(); }
        catch (e) { setError(e.message); }
    };

    const toggleStudent = (id) => {
        setSelectedStudents(prev => prev.includes(id) ? prev.filter(s => s !== id) : [...prev, id]);
    };

    const filtered = tests.filter(t => (t.title || '').toLowerCase().includes(searchTerm.toLowerCase()) || (t.company_name || '').toLowerCase().includes(searchTerm.toLowerCase()));
    const filteredStudents = allStudents.filter(s => (s.name || '').toLowerCase().includes(studentSearch.toLowerCase()) || (s.email || '').toLowerCase().includes(studentSearch.toLowerCase()));

    return (
        <div style={{ padding: '24px', maxWidth: '1200px', margin: '0 auto' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{ width: '42px', height: '42px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'linear-gradient(135deg, #3b82f6, #2563eb)' }}><Building2 size={22} color="white" /></div>
                    <div><h2 style={{ margin: 0, fontSize: '22px', fontWeight: 800, color: '#f1f5f9' }}>Company Interview Tests</h2><p style={{ margin: 0, fontSize: '13px', color: '#9ca3af' }}>Create & manage company-specific AI interviews</p></div>
                </div>
                <button onClick={() => { setShowCreate(!showCreate); setError(''); }} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '11px 22px', background: showCreate ? 'linear-gradient(135deg, #ef4444, #dc2626)' : 'linear-gradient(135deg, #3b82f6, #2563eb)', color: 'white', border: 'none', borderRadius: '10px', cursor: 'pointer', fontWeight: 700, fontSize: '14px', boxShadow: '0 2px 8px rgba(59,130,246,0.3)' }}>
                    {showCreate ? <><X size={18} /> Cancel</> : <><Plus size={18} /> Create Test</>}
                </button>
            </div>

            {error && <div style={{ background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', borderRadius: '10px', padding: '12px 16px', marginBottom: '16px', color: '#fca5a5', display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '13px' }}><span><XCircle size={14} style={{ verticalAlign: 'middle', marginRight: '6px' }} />{error}</span><button onClick={() => setError('')} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#fca5a5' }}><X size={16} /></button></div>}

            {showCreate && (
                <div style={{ background: 'linear-gradient(135deg, rgba(59,130,246,0.08), rgba(37,99,235,0.05))', borderRadius: '16px', padding: '24px', marginBottom: '28px', border: '1px solid rgba(59,130,246,0.2)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '20px' }}><Sparkles size={20} color="#3b82f6" /><h3 style={{ margin: 0, fontSize: '18px', fontWeight: 800, color: '#93c5fd' }}>Create Company Interview</h3></div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '14px' }}>
                        <div><label style={{ fontWeight: 600, fontSize: '12px', display: 'block', marginBottom: '6px', color: '#cbd5e1' }}>Company Name <span style={{ color: '#f87171' }}>*</span></label><input value={form.company_name} onChange={e => setForm({ ...form, company_name: e.target.value })} placeholder="e.g., Google, Zoho, TCS" style={{ width: '100%', padding: '11px 14px', borderRadius: '10px', border: '2px solid ' + (form.company_name ? '#3b82f6' : '#475569'), fontSize: '14px', boxSizing: 'border-box', outline: 'none', background: '#0f172a', color: '#f1f5f9' }} /></div>
                        <div><label style={{ fontWeight: 600, fontSize: '12px', display: 'block', marginBottom: '6px', color: '#cbd5e1' }}>Test Title <span style={{ color: '#f87171' }}>*</span></label><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="e.g., Senior Developer Evaluation" style={{ width: '100%', padding: '11px 14px', borderRadius: '10px', border: '2px solid #475569', fontSize: '14px', boxSizing: 'border-box', outline: 'none', background: '#0f172a', color: '#f1f5f9' }} /></div>
                    </div>
                    <div style={{ marginBottom: '14px' }}><label style={{ fontWeight: 600, fontSize: '12px', display: 'block', marginBottom: '6px', color: '#cbd5e1' }}>Description</label><textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Brief overview..." rows={2} style={{ width: '100%', padding: '11px 14px', borderRadius: '10px', border: '2px solid #475569', fontSize: '14px', boxSizing: 'border-box', outline: 'none', background: '#0f172a', color: '#f1f5f9', resize: 'none' }} /></div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '14px', marginBottom: '18px' }}>
                        <div><label style={{ fontWeight: 600, fontSize: '12px', display: 'block', marginBottom: '6px', color: '#cbd5e1' }}>Difficulty</label><div style={{ display: 'flex', gap: '8px' }}>{['easy', 'medium', 'hard'].map(d => <button key={d} onClick={() => setForm({ ...form, difficulty: d })} style={{ flex: 1, padding: '10px', borderRadius: '10px', cursor: 'pointer', background: form.difficulty === d ? ({ easy: '#22c55e', medium: '#f59e0b', hard: '#ef4444' }[d]) + '18' : '#0f172a', border: `2px solid ${form.difficulty === d ? ({ easy: '#22c55e', medium: '#f59e0b', hard: '#ef4444' }[d]) : '#475569'}`, color: form.difficulty === d ? ({ easy: '#4ade80', medium: '#fbbf24', hard: '#f87171' }[d]) : '#94a3b8', fontWeight: 700, fontSize: '13px', textTransform: 'capitalize' }}>{d}</button>)}</div></div>
                        <div><label style={{ fontWeight: 600, fontSize: '12px', display: 'block', marginBottom: '6px', color: '#cbd5e1' }}>Duration (minutes)</label><input type="number" value={form.duration_minutes} onChange={e => setForm({ ...form, duration_minutes: parseInt(e.target.value) || 60 })} min={15} max={180} style={{ width: '100%', padding: '11px 14px', borderRadius: '10px', border: '2px solid #475569', fontSize: '14px', boxSizing: 'border-box', outline: 'none', background: '#0f172a', color: '#f1f5f9' }} /></div>
                        <div><label style={{ fontWeight: 600, fontSize: '12px', display: 'block', marginBottom: '6px', color: '#cbd5e1' }}>Max Attempts <span style={{ fontSize: '10px', color: '#64748b' }}>(0 = unlimited)</span></label><input type="number" value={form.max_attempts} onChange={e => setForm({ ...form, max_attempts: parseInt(e.target.value) || 0 })} min={0} max={100} style={{ width: '100%', padding: '11px 14px', borderRadius: '10px', border: '2px solid #475569', fontSize: '14px', boxSizing: 'border-box', outline: 'none', background: '#0f172a', color: '#f1f5f9' }} /></div>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'flex-end' }}><button onClick={create} disabled={creating} style={{ padding: '12px 32px', background: creating ? '#6366f1' : 'linear-gradient(135deg, #3b82f6, #2563eb)', color: 'white', border: 'none', borderRadius: '10px', cursor: creating ? 'not-allowed' : 'pointer', fontWeight: 800, fontSize: '15px', display: 'flex', alignItems: 'center', gap: '8px' }}>{creating ? 'Creating...' : <><Sparkles size={16} /> Create Assessment</>}</button></div>
                </div>
            )}

            {!showCreate && <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '16px' }}><div style={{ position: 'relative' }}><Search size={16} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: '#9ca3af' }} /><input value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder="Search tests..." style={{ padding: '10px 14px 10px 36px', borderRadius: '10px', border: '1px solid #475569', background: '#0f172a', color: '#f1f5f9', fontSize: '13px', width: '280px', outline: 'none' }} /></div></div>}

            {loading ? <div style={{ textAlign: 'center', padding: '60px', color: '#9ca3af' }}><div style={{ width: '40px', height: '40px', border: '3px solid #e5e7eb', borderTopColor: '#3b82f6', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto 12px' }} /><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style><p style={{ fontSize: '14px' }}>Loading...</p></div>
                : filtered.length === 0 ? <div style={{ textAlign: 'center', padding: '60px', background: '#1e293b', borderRadius: '16px', border: '1px dashed #475569' }}><Building2 size={48} style={{ color: '#475569', marginBottom: '12px' }} /><h3 style={{ color: '#e2e8f0' }}>No tests found</h3><p style={{ color: '#94a3b8' }}>{searchTerm ? 'Try a different search' : 'Create your first company test'}</p></div>
                    : <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
                        <div style={{ fontSize: '13px', color: '#94a3b8', fontWeight: 600 }}>{filtered.length} test{filtered.length !== 1 ? 's' : ''}</div>
                        {filtered.map(test => (
                            <div key={test.id} style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '14px', padding: '20px', borderLeft: `4px solid ${test.is_active ? '#3b82f6' : '#475569'}` }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                    <div style={{ flex: 1 }}>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px', flexWrap: 'wrap' }}>
                                            <h3 style={{ margin: 0, fontSize: '17px', fontWeight: 800, color: '#f1f5f9' }}>{test.title}</h3>
                                            <span style={{ padding: '3px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: 700, background: test.is_active ? '#dcfce7' : '#fee2e2', color: test.is_active ? '#16a34a' : '#dc2626' }}>{test.is_active ? 'Active' : 'Inactive'}</span>
                                            <span style={{ padding: '3px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: 700, background: '#3b82f618', color: '#60a5fa' }}>{test.company_name}</span>
                                            <span style={{ padding: '3px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: 600, background: test.difficulty === 'hard' ? '#ef444418' : test.difficulty === 'medium' ? '#f59e0b18' : '#22c55e18', color: test.difficulty === 'hard' ? '#f87171' : test.difficulty === 'medium' ? '#fbbf24' : '#4ade80' }}>{test.difficulty}</span>
                                        </div>
                                        {test.description && <p style={{ margin: '0 0 10px', color: '#94a3b8', fontSize: '13px' }}>{test.description}</p>}

                                        {/* Attempt Limit Row */}
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', padding: '6px 12px', background: '#0f172a', borderRadius: '8px', width: 'fit-content' }}>
                                            <Shield size={14} color="#8b5cf6" />
                                            {editingLimit === test.id ? (
                                                <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                                                    <span style={{ fontSize: '12px', color: '#a78bfa', fontWeight: 600 }}>Attempts:</span>
                                                    <input type="number" value={limitValue} onChange={e => setLimitValue(e.target.value)} min={0} max={100} style={{ width: '60px', padding: '4px 8px', borderRadius: '6px', border: '1px solid #8b5cf6', background: '#1e293b', color: '#f1f5f9', fontSize: '12px', outline: 'none' }} autoFocus />
                                                    <button onClick={() => saveLimit(test.id)} style={{ padding: '4px 10px', borderRadius: '6px', background: '#22c55e20', border: '1px solid #22c55e40', color: '#4ade80', fontSize: '11px', fontWeight: 700, cursor: 'pointer' }}>Save</button>
                                                    <button onClick={() => setEditingLimit(null)} style={{ padding: '4px 8px', borderRadius: '6px', background: '#ef444420', border: '1px solid #ef444440', color: '#f87171', fontSize: '11px', cursor: 'pointer' }}>✕</button>
                                                </div>
                                            ) : (
                                                <>
                                                    <span style={{ fontSize: '12px', color: '#a78bfa', fontWeight: 600 }}>Attempts: {test.max_attempts > 0 ? test.max_attempts : 'Unlimited'}</span>
                                                    <button onClick={() => { setEditingLimit(test.id); setLimitValue(test.max_attempts || 0); }} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '2px', display: 'flex', fontSize: '14px' }} title="Edit limit">✏️</button>
                                                </>
                                            )}
                                        </div>

                                        <div style={{ display: 'flex', gap: '16px', fontSize: '12px' }}>
                                            <span style={{ color: '#94a3b8', display: 'flex', alignItems: 'center', gap: '4px' }}><Clock size={13} /> {test.duration_minutes}m</span>
                                            <span style={{ color: '#94a3b8', display: 'flex', alignItems: 'center', gap: '4px' }}><Users size={13} /> {test.total_attempts || 0} attempts</span>
                                            <span style={{ color: '#22c55e', display: 'flex', alignItems: 'center', gap: '4px' }}><CheckCircle2 size={13} /> {test.completed_attempts || 0} completed</span>
                                            {test.avg_score > 0 && <span style={{ color: '#60a5fa', display: 'flex', alignItems: 'center', gap: '4px' }}><BarChart2 size={13} /> Avg: {Math.round(test.avg_score)}%</span>}
                                        </div>
                                    </div>
                                    <div style={{ display: 'flex', gap: '6px', marginLeft: '16px', flexWrap: 'wrap' }}>
                                        <button onClick={() => loadAttempts(test.id)} title="View Attempts" style={{ padding: '8px', background: 'rgba(16,185,129,0.1)', border: '1px solid rgba(16,185,129,0.3)', borderRadius: '10px', cursor: 'pointer' }}><Eye size={16} color="#34d399" /></button>
                                        <button onClick={() => openAssignModal(test.id)} title="Assign Students" style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 14px', background: 'rgba(167,139,250,0.1)', color: '#a78bfa', border: '1px solid rgba(167,139,250,0.2)', borderRadius: '10px', fontSize: '12px', fontWeight: 600, cursor: 'pointer', transition: 'all 0.2s' }}
                                            onMouseEnter={e => e.currentTarget.style.background = 'rgba(167,139,250,0.2)'}
                                            onMouseLeave={e => e.currentTarget.style.background = 'rgba(167,139,250,0.1)'}
                                        ><Users size={16} /> Assign</button>
                                        <button onClick={() => toggle(test.id)} title={test.is_active ? 'Deactivate' : 'Activate'} style={{ padding: '8px', background: test.is_active ? 'rgba(245,158,11,0.1)' : 'rgba(16,185,129,0.1)', border: '1px solid ' + (test.is_active ? 'rgba(245,158,11,0.3)' : 'rgba(16,185,129,0.3)'), borderRadius: '10px', cursor: 'pointer' }}>{test.is_active ? <ToggleRight size={16} color="#fbbf24" /> : <ToggleLeft size={16} color="#34d399" />}</button>
                                        <button onClick={() => del(test.id)} title="Delete" style={{ padding: '8px 14px', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', borderRadius: '10px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', color: '#f87171', fontSize: '12px', fontWeight: 600 }}><Trash2 size={16} /> Delete</button>
                                    </div>
                                </div>
                                {viewAttempts === test.id && (
                                    <div style={{ marginTop: '16px', borderTop: '1px solid #334155', paddingTop: '16px' }}>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '12px' }}>
                                            <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 700, color: '#e2e8f0', display: 'flex', alignItems: 'center', gap: '6px' }}><Users size={15} /> Student Attempts</h4>
                                            <button onClick={() => setViewAttempts(null)} style={{ background: '#334155', border: 'none', cursor: 'pointer', color: '#94a3b8', borderRadius: '6px', padding: '4px 8px', fontSize: '11px', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '4px' }}>Close <ChevronUp size={14} /></button>
                                        </div>
                                        {attempts.length === 0 ? <p style={{ color: '#9ca3af', fontSize: '13px' }}>No attempts yet</p> : (
                                            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                                                <thead><tr style={{ background: '#0f172a' }}>{['Student', 'Stage', 'Score', 'Status', 'Date'].map(h => <th key={h} style={{ padding: '8px', textAlign: h === 'Student' ? 'left' : 'center', borderBottom: '1px solid #334155', color: '#94a3b8' }}>{h}</th>)}</tr></thead>
                                                <tbody>{attempts.map(a => (
                                                    <tr key={a.id} style={{ borderBottom: '1px solid #1e293b' }}>
                                                        <td style={{ padding: '8px', color: '#e2e8f0' }}>{a.student_name || a.student_id}</td>
                                                        <td style={{ padding: '8px', textAlign: 'center' }}><span style={{ padding: '2px 8px', borderRadius: '12px', fontSize: '11px', background: 'rgba(99,102,241,0.15)', color: '#a5b4fc' }}>{a.current_stage}</span></td>
                                                        <td style={{ padding: '8px', textAlign: 'center', fontWeight: 700, color: '#f1f5f9' }}>{a.overall_score > 0 ? `${Math.round(a.overall_score)}%` : '-'}</td>
                                                        <td style={{ padding: '8px', textAlign: 'center' }}><span style={{ padding: '2px 8px', borderRadius: '12px', fontSize: '11px', fontWeight: 600, background: a.status === 'completed' ? 'rgba(16,185,129,0.15)' : 'rgba(245,158,11,0.15)', color: a.status === 'completed' ? '#6ee7b7' : '#fcd34d' }}>{a.status}</span></td>
                                                        <td style={{ padding: '8px', textAlign: 'center', color: '#94a3b8', fontSize: '11px' }}>{new Date(a.started_at).toLocaleDateString()}</td>
                                                    </tr>
                                                ))}</tbody>
                                            </table>
                                        )}
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>}

            {/* Assign Students Modal */}
            {assignModal && (
                <div style={{ position: 'fixed', inset: 0, zIndex: 9999, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <div style={{ background: '#1e293b', borderRadius: '20px', width: '520px', maxHeight: '80vh', display: 'flex', flexDirection: 'column', border: '1px solid #334155', boxShadow: '0 20px 60px rgba(0,0,0,0.5)' }}>
                        <div style={{ padding: '20px 24px', borderBottom: '1px solid #334155', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                            <h2 style={{ margin: 0, fontSize: '1.3rem', color: '#f1f5f9', fontWeight: 800 }}>Assign Students</h2>
                            <button onClick={() => setAssignModal(null)} style={{ background: '#334155', border: 'none', cursor: 'pointer', color: '#94a3b8', borderRadius: '8px', padding: '6px', display: 'flex' }}><X size={18} /></button>
                        </div>
                        <div style={{ padding: '16px 24px', borderBottom: '1px solid #334155' }}>
                            <div style={{ position: 'relative' }}>
                                <Search size={16} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: '#64748b' }} />
                                <input value={studentSearch} onChange={e => setStudentSearch(e.target.value)} placeholder="Search students..." style={{ width: '100%', padding: '10px 14px 10px 38px', borderRadius: '10px', border: '1px solid #475569', background: '#0f172a', color: '#f1f5f9', fontSize: '13px', outline: 'none', boxSizing: 'border-box' }} />
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '10px', fontSize: '12px', color: '#64748b' }}>
                                <span>{selectedStudents.length} selected</span>
                                <div style={{ display: 'flex', gap: '8px' }}>
                                    <button onClick={() => setSelectedStudents(allStudents.map(s => s.id))} style={{ background: 'none', border: 'none', color: '#60a5fa', fontSize: '12px', cursor: 'pointer', fontWeight: 600 }}>Select All</button>
                                    <button onClick={() => setSelectedStudents([])} style={{ background: 'none', border: 'none', color: '#f87171', fontSize: '12px', cursor: 'pointer', fontWeight: 600 }}>Clear</button>
                                </div>
                            </div>
                        </div>
                        <div style={{ flex: 1, overflowY: 'auto', padding: '12px 24px', maxHeight: '350px' }}>
                            {filteredStudents.length === 0 ? <p style={{ textAlign: 'center', color: '#64748b', padding: '20px' }}>No students found</p> :
                                filteredStudents.map(s => (
                                    <label key={s.id} style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 12px', borderRadius: '10px', cursor: 'pointer', transition: 'all 0.15s', background: selectedStudents.includes(s.id) ? 'rgba(59,130,246,0.1)' : 'transparent', border: `1px solid ${selectedStudents.includes(s.id) ? 'rgba(59,130,246,0.3)' : 'transparent'}`, marginBottom: '4px' }}>
                                        <input type="checkbox" checked={selectedStudents.includes(s.id)} onChange={() => toggleStudent(s.id)} style={{ accentColor: '#3b82f6', width: '16px', height: '16px' }} />
                                        <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: '#3b82f620', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#60a5fa', fontWeight: 700, fontSize: '13px' }}>{(s.name || '?')[0].toUpperCase()}</div>
                                        <div><div style={{ fontWeight: 600, fontSize: '13px', color: '#f1f5f9' }}>{s.name}</div><div style={{ fontSize: '11px', color: '#64748b' }}>{s.email}</div></div>
                                    </label>
                                ))
                            }
                        </div>
                        <div style={{ padding: '16px 24px', borderTop: '1px solid #334155', display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                            <button onClick={() => setAssignModal(null)} style={{ padding: '10px 20px', borderRadius: '10px', border: '1px solid #475569', background: 'none', color: '#94a3b8', fontWeight: 600, cursor: 'pointer', fontSize: '13px' }}>Cancel</button>
                            <button onClick={saveAssignment} style={{ padding: '10px 24px', borderRadius: '10px', border: 'none', background: 'linear-gradient(135deg, #3b82f6, #2563eb)', color: 'white', fontWeight: 700, cursor: 'pointer', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}><CheckCircle2 size={16} /> Confirm Assignments</button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}


